"""empty message

Revision ID: 29840ed9de33
Revises: 548ba2d9fec9
Create Date: 2017-07-28 12:42:24.157628

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '29840ed9de33'
down_revision = '548ba2d9fec9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('sendmessage_message_key', 'sendmessage', type_='unique')
    op.drop_constraint('sendmessage_state_key', 'sendmessage', type_='unique')
    op.drop_constraint('sendmessage_to_key', 'sendmessage', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('sendmessage_to_key', 'sendmessage', ['to'])
    op.create_unique_constraint('sendmessage_state_key', 'sendmessage', ['state'])
    op.create_unique_constraint('sendmessage_message_key', 'sendmessage', ['message'])
    # ### end Alembic commands ###
