"""empty message

Revision ID: 548ba2d9fec9
Revises: c7a115af1e4a
Create Date: 2017-07-27 21:39:25.474712

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '548ba2d9fec9'
down_revision = 'c7a115af1e4a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('partner', sa.Column('address', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('partner', 'address')
    # ### end Alembic commands ###
