"""empty message

Revision ID: 71d0f6372175
Revises: 37054b074868
Create Date: 2017-08-14 20:44:56.530979

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '71d0f6372175'
down_revision = '37054b074868'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('responseerror',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('responseerror')
    # ### end Alembic commands ###
