"""empty message

Revision ID: 9879ab828d0a
Revises: f55b4376c4f2
Create Date: 2017-08-10 21:16:45.918447

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9879ab828d0a'
down_revision = 'f55b4376c4f2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sendmessage', sa.Column('conversationType', sa.String(length=120), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sendmessage', 'conversationType')
    # ### end Alembic commands ###
