"""empty message

Revision ID: fb9497d1def7
Revises: 9879ab828d0a
Create Date: 2017-08-10 21:31:20.308346

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fb9497d1def7'
down_revision = '9879ab828d0a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('event', sa.Column('audience', sa.String(length=120), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('event', 'audience')
    # ### end Alembic commands ###
